apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-services
spec:
  template:
    spec:
      containers:
        - name: backend-services
          resources:
            limits:
              memory: "2Gi"
