apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-worker-logs
  labels:
    app: temporal-worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
