apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  to:
    kind: Service
    name: temporal-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
