server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: host-apps
    static_configs:
      - targets: [localhost]
        labels:
          service: backend-services
          project: host
          __path__: /var/log/host-apps/backend-services.log
      - targets: [localhost]
        labels:
          service: frontend
          project: host
          __path__: /var/log/host-apps/frontend.log
      - targets: [localhost]
        labels:
          service: temporal-worker
          project: host
          __path__: /var/log/host-apps/temporal-worker.log
