apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fd34fb-test
resources:
- ../../base
images:
- name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/backend-services
  newTag: develop-latest
- name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/temporal
  newTag: develop-latest
- name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/frontend
  newTag: develop-latest
commonLabels:
  env: dev


