apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plg.alertmanager.fullname" . }}-config
  labels:
    {{- include "plg.alertmanager.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: {{ .Values.alertmanager.resolveTimeout }}

    route:
      receiver: "drop"
      group_by:
        {{- range .Values.alertmanager.route.groupBy }}
        - {{ . | quote }}
        {{- end }}
      group_wait: {{ .Values.alertmanager.route.groupWait }}
      group_interval: {{ .Values.alertmanager.route.groupInterval }}
      repeat_interval: {{ .Values.alertmanager.route.repeatInterval }}
      {{- if .Values.alertmanager.notificationsEnabled }}
      routes:
        - receiver: {{ printf "%s-notifications" .Values.alertmanager.notificationChannel | quote }}
          matchers:
          {{- if eq .Values.alertmanager.minNotificationSeverity "critical" }}
            - 'severity = "critical"'
          {{- else }}
            - 'severity =~ "warning|critical"'
          {{- end }}
        - receiver: "drop"
      {{- end }}

    receivers:
      - name: "drop"
      {{- if eq .Values.alertmanager.notificationChannel "teams" }}
      - name: "teams-notifications"
        webhook_configs:
          - url: {{ .Values.alertmanager.teams.webhookUrl | quote }}
            send_resolved: true
      {{- end }}
      {{- if eq .Values.alertmanager.notificationChannel "ches" }}
      - name: "ches-notifications"
        webhook_configs:
          - url: {{ .Values.alertmanager.ches.apiUrl | quote }}
            send_resolved: true
            http_config:
              oauth2:
                client_id: {{ .Values.alertmanager.ches.clientId | quote }}
                client_secret: {{ .Values.alertmanager.ches.clientSecret | quote }}
                token_url: {{ .Values.alertmanager.ches.tokenUrl | quote }}
      {{- end }}
