apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plg.alertmanager.fullname" . }}
  labels:
    {{- include "plg.alertmanager.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "plg.alertmanager.fullname" . }}
  selector:
    matchLabels:
      {{- include "plg.alertmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plg.alertmanager.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/alertmanager-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - name: http
              containerPort: {{ .Values.alertmanager.httpPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /alertmanager
            {{- if and .Values.alertmanager.notificationsEnabled (eq .Values.alertmanager.notificationChannel "ches") }}
            - name: adapter-credentials
              mountPath: /etc/alertmanager-secrets
              readOnly: true
            {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      volumes:
        - name: config
          configMap:
            name: {{ include "plg.alertmanager.fullname" . }}-config
        {{- if and .Values.alertmanager.notificationsEnabled (eq .Values.alertmanager.notificationChannel "ches") }}
        - name: adapter-credentials
          secret:
            secretName: {{ include "plg.alertmanager.adapterSecretName" . }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "plg.alertmanager.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.alertmanager.storageClassName }}
        storageClassName: {{ .Values.alertmanager.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.alertmanager.pvcSize }}
