apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plg.grafana.fullname" . }}-data
  labels:
    {{- include "plg.grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.pvcSize }}
  {{- if .Values.grafana.storageClassName }}
  storageClassName: {{ .Values.grafana.storageClassName }}
  {{- end }}
