apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plg.grafana.fullname" . }}-datasources
  labels:
    {{- include "plg.grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "plg.prometheus.fullname" . }}:{{ .Values.prometheus.httpPort }}
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ include "plg.loki.fullname" . }}:{{ .Values.loki.httpPort }}
        isDefault: false
        editable: false
