apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plg.grafana.fullname" . }}-config
  labels:
    {{- include "plg.grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    http_port = {{ .Values.grafana.httpPort }}
    root_url = %(protocol)s://%(domain)s:%(http_port)s/

    [security]
    admin_user = {{ .Values.grafana.adminUser }}

    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [users]
    allow_sign_up = false

    [auth]
    disable_login_form = false

    [paths]
    provisioning = /etc/grafana/provisioning
