apiVersion: v1
kind: Service
metadata:
  name: {{ include "plg.grafana.fullname" . }}
  labels:
    {{- include "plg.grafana.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.grafana.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "plg.grafana.selectorLabels" . | nindent 4 }}
