apiVersion: v1
kind: Service
metadata:
  name: {{ include "plg.loki.fullname" . }}
  labels:
    {{- include "plg.loki.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.loki.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "plg.loki.selectorLabels" . | nindent 4 }}
