apiVersion: v1
kind: Service
metadata:
  name: {{ include "plg.prometheus.fullname" . }}
  labels:
    {{- include "plg.prometheus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "plg.prometheus.selectorLabels" . | nindent 4 }}
