apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plg.prometheus.fullname" . }}-rules
  labels:
    {{- include "plg.prometheus.labels" . | nindent 4 }}
data:
  app-alerts.yml: |
    {{- .Files.Get "files/app-alerts.yml" | nindent 4 }}
