apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plg.prometheus.fullname" . }}-config
  labels:
    {{- include "plg.prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: "backend-services"
        metrics_path: "/metrics"
        scrape_interval: {{ .Values.prometheus.scrapeInterval }}
        static_configs:
          - targets:
              - "{{ .Values.prometheus.scrapeTargets.backendServices.host }}:{{ .Values.prometheus.scrapeTargets.backendServices.port }}"

      - job_name: "temporal-server"
        metrics_path: "/metrics"
        scrape_interval: {{ .Values.prometheus.scrapeInterval }}
        static_configs:
          - targets:
              - "{{ .Values.prometheus.scrapeTargets.temporalServer.host }}:{{ .Values.prometheus.scrapeTargets.temporalServer.port }}"
