name: Migrate DB Schema
description: 'Migrate DB Schema'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'test'
  openshift-server:
    description: 'OpenShift server'
    required: true
  api-token:
    description: 'OpenShift service account API token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Migrate Database
      run: |
        chmod +x ./.github/actions/migrate-db/migrate.sh
        ./.github/actions/migrate-db/migrate.sh "${{ inputs.environment }}" "${{ inputs.openshift-server }}" "${{ inputs.api-token }}"
      shell: bash