import { GroupRole } from "@/generated";

// No need to include system-admin-only permissions here.
export enum Permission {
  // API-keys
  API_KEY_RETRIEVE,
  API_KEY_CREATE,
  API_KEY_DELETE,
  // Benchmarks
  BENCHMARK_CREATE,
  BENCHMARK_RETRIEVE,
  BENCHMARK_UPDATE,
  BENCHMARK_SCHEDULE,
  BENCHMARK_DELETE,
  BENCHMARK_FILES,
  // Classifiers
  CLASSIFIER_RETRIEVE,
  CLASSIFIER_CREATE,
  CLASSIFIER_UPDATE,
  CLASSIFIER_USE,
  CLASSIFIER_FILES,
  CLASSIFIER_TRAIN,
  CLASSIFIER_DELETE,
  // Confusion Profiles
  CONFUSION_CREATE,
  CONFUSION_RETRIEVE,
  CONFUSION_UPDATE,
  CONFUSION_DELETE,
  // Documents
  DOCUMENT_RETRIEVE,
  DOCUMENT_CREATE,
  DOCUMENT_DELETE,
  DOCUMENT_UPDATE,
  DOCUMENT_VIEW,
  DOCUMENT_DOWNLOAD,
  // Groups
  // GROUP_CREATE, // Should only be system-admin
  // GROUP_DELETE, // Should only be system-admin
  GROUP_UPDATE,
  GROUP_RETRIEVE,
  GROUP_REQUESTS_RETRIEVE,
  GROUP_REQUESTS_APPROVE_DENY,
  GROUP_USER_REMOVE,
  GROUP_USER_ADD,
  GROUP_USER_ROLE_UPDATE,
  // HITL
  HITL_QUEUE_RETRIEVE,
  HITL_SESSION_RETRIEVE,
  HITL_SESSION_PROGRESS,
  HITL_SESSION_REOPEN,
  HITL_CORRECTION_SUBMIT,
  HITL_CORRECTION_RETRIEVE,
  HITL_CORRECTION_DELETE,
  HITL_DATASET_CREATE,
  HITL_DATASET_RETRIEVE,
  HITL_DATASET_UPDATE,
  HITL_APPROVE_DENY,
  // OCR
  OCR_RESULTS_RETRIEVE,
  OCR_MODELS_RETRIEVE,
  OCR_REPROCESS,
  // Tables
  TABLE_RETRIEVE,
  TABLE_CREATE,
  TABLE_UPDATE,
  TABLE_DELETE,
  TABLE_COLUMN_CREATE,
  TABLE_COLUMN_UPDATE,
  TABLE_COLUMN_DELETE,
  TABLE_ROW_CREATE,
  TABLE_ROW_UPDATE,
  TABLE_ROW_DELETE,
  // Template Models
  TEMPLATE_MODEL_RETRIEVE,
  TEMPLATE_MODEL_UPDATE,
  TEMPLATE_MODEL_DELETE,
  TEMPLATE_MODEL_FIELDS_RETRIEVE,
  TEMPLATE_MODEL_FIELDS_CREATE,
  TEMPLATE_MODEL_FIELDS_UPDATE,
  TEMPLATE_MODEL_FIELDS_DELETE,
  TEMPLATE_MODEL_DOCUMENT_RETRIEVE,
  TEMPLATE_MODEL_DOCUMENT_CREATE,
  TEMPLATE_MODEL_DOCUMENT_DELETE,
  TEMPLATE_MODEL_LABEL_RETRIEVE,
  TEMPLATE_MODEL_LABEL_CREATE,
  TEMPLATE_MODEL_LABEL_DELETE,
  TEMPLATE_MODEL_SUGGESTIONS,
  TEMPLATE_MODEL_EXPORT,
  // Training
  TRAINING_RETRIEVE,
  TRAINING_CREATE,
  TRAINING_DELETE,
  // Workflows
  WORKFLOW_RETREIVE,
  WORKFLOW_CREATE,
  WORKFLOW_UPDATE,
  WORKFLOW_DELETE,
}

const { ADMIN, MEMBER, REVIEWER } = GroupRole;

const allPermissions = Object.values(Permission) as Permission[];

// Reminder that this is group admins only, not system-admins.
const groupAdminOnlyPermissions = [
  Permission.GROUP_UPDATE,
  Permission.GROUP_REQUESTS_APPROVE_DENY,
  Permission.GROUP_REQUESTS_RETRIEVE,
  Permission.GROUP_USER_ADD,
  Permission.GROUP_USER_REMOVE,
  Permission.GROUP_USER_ROLE_UPDATE,
];

export const RoleClaimsMap: Record<GroupRole, Permission[]> = {
  [ADMIN]: allPermissions,
  [MEMBER]: allPermissions.filter(
    (p) => !groupAdminOnlyPermissions.includes(p),
  ),
  [REVIEWER]: [
    Permission.HITL_CORRECTION_DELETE,
    Permission.HITL_CORRECTION_RETRIEVE,
    Permission.HITL_CORRECTION_SUBMIT,
    Permission.HITL_QUEUE_RETRIEVE,
    Permission.HITL_SESSION_PROGRESS,
    Permission.HITL_SESSION_REOPEN,
    Permission.HITL_SESSION_RETRIEVE,
    Permission.GROUP_RETRIEVE,
  ],
};
