/**
 * Phase 4 — Try-in-place. Local TypeScript mirror of the backend's
 * `NodeRunStatusDto` (apps/backend-services/src/workflow/dto/node-statuses-response.dto.ts).
 *
 * Per [TRY_IN_PLACE_DESIGN.md §3.3](../../../../../../docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md)
 * Phase 4 follows the local-mirror pattern (consistent with the other
 * Phase 2/8 hooks under `data/hooks/useWorkflows.ts`) rather than
 * autogenerated OpenAPI types — the wire shape is small and the
 * backend DTO is the source of truth. Keep these two declarations
 * aligned when the backend DTO evolves.
 *
 * Spec refs:
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/REQUIREMENTS.md L29
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/user_stories/US-137-use-node-statuses-hook.md
 *   - docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md §3.3
 */

/**
 * Lifecycle state of a single node within a workflow run. `cancelled`
 * is not a value the backend currently writes (the workflow runtime
 * emits `pending` | `running` | `succeeded` | `failed` | `skipped`),
 * but the design doc reserves it for the future workflow-cancel path
 * and the hook's terminal-state check (§3.3) explicitly includes it
 * so that consumers don't need updates when cancel lands.
 */
export type NodeRunStatusValue =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "skipped"
  | "cancelled";

/**
 * Cache-hit metadata. Populated only when `status === "skipped"` —
 * the Phase 4 cache decorator (US-128) records which cache row served
 * the output so the canvas can surface "served from cache" UX.
 */
export interface NodeRunStatusCacheHit {
  configHash: string;
  inputHash: string;
}

/**
 * Per-node live run status surfaced to the canvas. Mirrors the backend
 * `NodeRunStatusDto` shape (US-136). All timestamps are ISO-8601.
 */
export interface NodeRunStatus {
  status: NodeRunStatusValue;
  /** ISO-8601 — populated the moment the node entered `running`. */
  startedAt?: string;
  /** ISO-8601 — populated the moment the node left `running`. */
  endedAt?: string;
  /** Populated when `status === "failed"`. The thrown error's `.message`. */
  errorMessage?: string;
  /** Populated when `status === "skipped"`. Names the cache row served. */
  cacheHit?: NodeRunStatusCacheHit;
}

/**
 * The wire body of `GET /api/workflows/:id/runs/:runId/node-statuses`.
 * Nodes the workflow never walked stay absent from the map — the
 * canvas treats "absent" as "pending" (see US-138).
 */
export type NodeStatusesMap = Record<string, NodeRunStatus>;

/**
 * Status values that count as terminal for the polling-stop check in
 * §3.3. Once every node in the map is in one of these states, the
 * polling interval is disabled.
 */
export const TERMINAL_NODE_STATUSES: readonly NodeRunStatusValue[] = [
  "succeeded",
  "failed",
  "skipped",
  "cancelled",
];
