/**
 * This file shows some examples of how integration tests can be written.
 * Do not edit this file unless you are adding additional examples.
 */

import TestAgent from "supertest/lib/agent";
import { PrismaClient } from "../src/generated/client";
import { closeDb, openDb } from "./helpers/db-conn";
import { CompositeMockGuard, httpServiceMock } from "./helpers/test-app.module";
import setupTestModule from "./helpers/test-app-setup";

describe("how to manipulate database before/after test", () => {
  let db: PrismaClient;
  beforeAll(async () => {
    // Insert dummy document
    db = openDb();
    await db.document.create({
      data: {
        title: "Test Document",
        original_filename: "test.pdf",
        file_path: "/tmp/test.pdf",
        file_type: "pdf",
        file_size: 12345,
        source: "integration-test",
        status: "pre_ocr",
      },
    });
  });

  afterAll(async () => {
    await db.document.deleteMany();
    await closeDb(db);
  });

  it("is in the database", async () => {
    const doc = await db.document.findFirst({
      where: { source: "integration-test" },
    });
    expect(doc).toBeTruthy();
    expect(doc?.title).toBe("Test Document");
  });
});

// Integration test for the protected route
describe("how to mock Keycloak with app", () => {
  const testModule = setupTestModule();
  let agent: TestAgent;

  beforeAll(async () => {
    agent = await testModule.open();
  });

  afterAll(async () => {
    await testModule.close();
  });

  it("should return protected data and user info (default user)", async () => {
    // Mocking goes like this. There is a default.
    CompositeMockGuard.mockUser = {
      idir_username: "testuser",
      display_name: "Test User",
      email: "test@example.com",
      roles: ["user", "admin"],
    };
    const res = await agent.get("/api/protected").expect(200);
    expect(res.body).toHaveProperty("message", "Protected data");
    expect(res.body).toHaveProperty("user");
    expect(res.body.user).toMatchObject({
      idirUsername: "testuser",
      displayName: "Test User",
      email: "test@example.com",
    });
  });
});

describe("how to override HTTP mock per test", () => {
  afterEach(() => {
    // Reset mock to default after each test
    httpServiceMock.post.mockReset();
    httpServiceMock.get.mockReset();
  });

  it("should simulate a failed OCR response", async () => {
    httpServiceMock.post.mockReturnValueOnce({
      toPromise: async () => ({ status: 400, headers: {} }),
      subscribe: () => {},
    });
    // ...call your service or endpoint that triggers POST here...
    // Example assertion:
    const response = await httpServiceMock.post().toPromise();
    expect(response.status).toBe(400);
  });

  it("should simulate a custom GET response", async () => {
    httpServiceMock.get.mockReturnValueOnce({
      toPromise: async () => ({
        status: 200,
        data: {
          status: "succeeded",
          createdDateTime: "2026-01-01T00:00:00.000Z",
          lastUpdatedDateTime: "2026-01-01T00:00:00.000Z",
          analyzeResult: { content: "custom-content", pages: [1, 2] },
        },
      }),
      subscribe: () => {},
    });
    // ...call your service or endpoint that triggers GET here...
    // Example assertion:
    const response = await httpServiceMock.get().toPromise();
    expect(response.data.analyzeResult.content).toBe("custom-content");
    expect(response.data.analyzeResult.pages).toEqual([1, 2]);
  });
});
