apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-services-config
data:
  FRONTEND_URL: "https://frontend-fd34fb-prod.apps.silver.devops.gov.bc.ca"
  BACKEND_URL: "https://backend-services-fd34fb-prod.apps.silver.devops.gov.bc.ca"
  SSO_REDIRECT_URI: "https://backend-services-fd34fb-prod.apps.silver.devops.gov.bc.ca/api/auth/callback"
  SSO_AUTH_SERVER_URL: "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect"
  SSO_REALM: "standard"
  SSO_CLIENT_ID: "ai-adoption-document-intelligence-6162"
