
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend-services
spec:
  lookupPolicy:
    local: false
  tags:
    - name: develop-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/backend-services:develop-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: stage-latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/backend-services:stage-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: latest
      from:
        kind: DockerImage
        name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/backend-services:main-latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
