apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - route.yml
  - configmap.yml
  - pvc.yml
  - pvc-logs.yml
  - logrotate-configmap.yml
  - networkpolicy.yml
commonLabels:
  app: backend-services
  env: tools

