apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-services-logrotate
  labels:
    app: backend-services
data:
  backend: |
    /var/log/app/backend.log {
        copytruncate
        rotate 5
        size 50M
        missingok
        notifempty
    }
