apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-services-logs
  labels:
    app: backend-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
