apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-services-storage
  labels:
    app: backend-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: netapp-file-standard
  resources:
    requests:
      storage: 2Gi

