apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-services-storage
  labels:
    app: backend-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  # storageClassName can be set via kustomize patches for different environments
  # Note: ReadWriteMany requires a storage class that supports it (e.g., NFS-based storage)

