/**
 * Phase 4 — Try-in-place. Local TypeScript mirror of the backend's
 * `ActivityOutputPreviewDto` (apps/backend-services/src/workflow/dto/
 * activity-output-preview.dto.ts).
 *
 * Per [TRY_IN_PLACE_DESIGN.md §4.1](../../../../../../docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md)
 * Phase 4 follows the local-mirror pattern (consistent with the other
 * Phase 2/8 hooks under `data/hooks/useWorkflows.ts`) rather than
 * autogenerated OpenAPI types — the wire shape is small and the
 * backend DTO is the source of truth. Keep these two declarations
 * aligned when the backend DTO evolves.
 *
 * Spec refs:
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/REQUIREMENTS.md L20 + L30 + L34
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/user_stories/US-141-preview-hook-and-dispatch-shell.md
 *   - docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md §4.1 + §4.6
 */

/**
 * One previewable output of a node (G-011). The canvas projection derives
 * these from the node's output BINDINGS joined with its activity-catalog
 * output DESCRIPTORS, and the preview widget renders one per port with a
 * selector when there is more than one.
 */
export interface PreviewOutputBinding {
  /** Output port name (the catalog descriptor's `name`). */
  port: string;
  /** Label for the port selector; falls back to the port name. */
  label: string;
  /** The ctx key this port's value is bound to inside the `outputCtx` delta. */
  ctxKey: string;
  /**
   * The port's declared artifact kind, from the catalog descriptor. Absent for
   * ports with no catalog entry (`dyn.*` activities, deleted entries) — the
   * value then renders through the generic fallback.
   */
  kind?: string;
}

/**
 * Wire shape of `GET /api/workflows/:id/preview-cache`. Mirrors the
 * backend `ActivityOutputPreviewDto`.
 */
export interface ActivityOutputPreview {
  /**
   * The ctx fragment this activity wrote. The shape is dictated by the
   * node's `outputKind`. Consumers must not assume any particular keys
   * outside what the dispatch shell extracts.
   */
  outputCtx: Record<string, unknown>;
  /**
   * The `ArtifactKind` (or `${ArtifactKind}[]`) literal the row's
   * `outputCtx` conforms to. `null` when the producing node did not
   * declare an output kind — the dispatch shell renders nothing in
   * that case.
   */
  outputKind: string | null;
  /** ISO-8601 — when the worker decorator wrote this cache row. */
  createdAt: string;
  /** ISO-8601 — when the row is considered expired by the read endpoint. */
  expiresAt: string;
  /**
   * G-022 — blob-backed values found in `outputCtx`, resolved server-side into
   * bounded excerpts and keyed by `blobPath`. `OcrResult` values are POINTERS
   * by design (large payloads stay out of ctx), so without this the preview
   * could only show `blobPath` / `byteLength` / `status`. Absent when the row
   * holds no pointers.
   */
  blobExcerpts?: Record<string, BlobExcerpt>;
}

/** Why a pointer could not be dereferenced. Mirrors the backend DTO. */
export type BlobExcerptUnavailableReason =
  | "not-found"
  | "unreadable"
  | "too-large"
  | "outside-group"
  | "request-limit";

/** The limits the server applied when building an excerpt. */
export interface BlobExcerptLimits {
  maxStringChars: number;
  maxArrayItems: number;
  maxObjectKeys: number;
  maxDepth: number;
  maxTotalChars: number;
}

/**
 * A blob-backed value the server dereferenced. Local mirror of the backend
 * `BlobExcerptDto`.
 */
export interface BlobExcerpt {
  blobPath: string;
  status: "resolved" | "unavailable";
  reason?: BlobExcerptUnavailableReason;
  /** Present only when `status === "resolved"`. */
  excerpt?: unknown;
  truncated: boolean;
  /**
   * Path-anchored notes for everything the server left out, e.g.
   * `pages: showing the first 5 of 300 items`. Rendered verbatim — a truncated
   * preview must always say it is truncated.
   */
  omissions: string[];
  byteLength?: number;
  limits: BlobExcerptLimits;
}
