/**
 * Phase 4 — Try-in-place. Local TypeScript mirror of the backend's
 * `ActivityOutputPreviewDto` (apps/backend-services/src/workflow/dto/
 * activity-output-preview.dto.ts).
 *
 * Per [TRY_IN_PLACE_DESIGN.md §4.1](../../../../../../docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md)
 * Phase 4 follows the local-mirror pattern (consistent with the other
 * Phase 2/8 hooks under `data/hooks/useWorkflows.ts`) rather than
 * autogenerated OpenAPI types — the wire shape is small and the
 * backend DTO is the source of truth. Keep these two declarations
 * aligned when the backend DTO evolves.
 *
 * Spec refs:
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/REQUIREMENTS.md L20 + L30 + L34
 *   - feature-docs/20260531-workflow-builder-phase4-try-in-place/user_stories/US-141-preview-hook-and-dispatch-shell.md
 *   - docs-md/workflow-builder/TRY_IN_PLACE_DESIGN.md §4.1 + §4.6
 */

/**
 * Wire shape of `GET /api/workflows/:id/preview-cache`. Mirrors the
 * backend `ActivityOutputPreviewDto`.
 */
export interface ActivityOutputPreview {
  /**
   * The ctx fragment this activity wrote. The shape is dictated by the
   * node's `outputKind`. Consumers must not assume any particular keys
   * outside what the dispatch shell extracts.
   */
  outputCtx: Record<string, unknown>;
  /**
   * The `ArtifactKind` (or `${ArtifactKind}[]`) literal the row's
   * `outputCtx` conforms to. `null` when the producing node did not
   * declare an output kind — the dispatch shell renders nothing in
   * that case.
   */
  outputKind: string | null;
  /** ISO-8601 — when the worker decorator wrote this cache row. */
  createdAt: string;
  /** ISO-8601 — when the row is considered expired by the read endpoint. */
  expiresAt: string;
}
