#!/bin/bash
set -e

# Run TypeScript checking for backend-services
(cd apps/backend-services && npx tsc --noEmit)

# Run Prettier formatting for backend-services
(cd apps/backend-services && npm run format)

# Run linting for backend-services
(cd apps/backend-services && npm run lint)

# Run TypeScript checking for frontend
(cd apps/frontend && npx tsc --noEmit)

# Run linting for frontend
(cd apps/frontend && npm run lint)